_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/DeFRCN/ImageNetPretrained/MSRA/"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
DATASETS:
  TRAIN: ('coco14_trainval_novel_1shot_seedx',)
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (800,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
PCB_MODELPATH: "/root/DeFRCN/ImageNetPretrained/torchvision"
OUTPUT_DIR: "/root/DeFRCN/checkpoints/voc/new/defrcn_det_r101_base2"
