_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/DeFRCN/ImageNetPretrained/MSRA/"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 1 #15
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base4', 'voc_2012_trainval_base4')
  TEST: ('voc_2007_test_base4',)
SOLVER:
  STEPS: (10000, 13300)
  MAX_ITER: 15 #15000
  CHECKPOINT_PERIOD: 200 #200000
  WARMUP_ITERS: 5 #100
OUTPUT_DIR: "/root/DeFRCN/checkpoints/voc/defrcn_one/"
