_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/DeFRCN/ImageNetPretrained/MSRA/"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 1
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novel4_1shot_seed4", )
  TEST: ('voc_2007_test_novel4',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (640, )
  MAX_ITER: 800
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
PCB_MODELPATH: "/root/DeFRCN/ImageNetPretrained/torchvision"
OUTPUT_DIR: "/root/DeFRCN/checkpoints/voc/new/defrcn_det_r101_base2"
